import { type Unit } from "src/constants/interface";
export const units: { [key: number]: Unit } = {
  88: {
    id: 1,
    name: "Test88",
    imagePath: "1005",
    life: 1,
    attack: 1,
    description: "",
    skillIds: [],
  },
  1: {
    id: 1,
    name: "Ant1",
    imagePath: "1001",
    life: 3,
    attack: 3,
    description: "",
    skillIds: [],
  },
  2: {
    id: 2,
    name: "Ant2",
    imagePath: "1002",
    life: 4,
    attack: 3,
    description: "",
    skillIds: [],
  },
  3: {
    id: 3,
    name: "Ant3",
    imagePath: "1003",
    life: 4,
    attack: 4,
    description: "",
    skillIds: [],
  },
  4: {
    id: 4,
    name: "Ant4",
    imagePath: "1004",
    life: 5,
    attack: 4,
    description: "",
    skillIds: [],
  },
  5: {
    id: 5,
    name: "Ant5",
    imagePath: "1005",
    life: 3,
    attack: 3,
    description: "",
    skillIds: [12],
  },
  6: {
    id: 6,
    name: "Ant6",
    imagePath: "1006",
    life: 9,
    attack: 3,
    description: "",
    skillIds: [],
  },
  7: {
    id: 7,
    name: "Ant7",
    imagePath: "1007",
    life: 2,
    attack: 8,
    description: "",
    skillIds: [],
  },
  8: {
    id: 8,
    name: "Ant8",
    imagePath: "1008",
    life: 6,
    attack: 6,
    description: "",
    skillIds: [],
  },
  8001: {
    id: 8001,
    name: "Ant1",
    imagePath: "8001",
    life: 2,
    attack: 2,
    description: "",
    skillIds: [],
  },
  8002: {
    id: 8002,
    name: "Ant1",
    imagePath: "8002",
    life: 2,
    attack: 3,
    description: "",
    skillIds: [],
  },
  8003: {
    id: 8003,
    name: "Ant1",
    imagePath: "8003",
    life: 3,
    attack: 4,
    description: "",
    skillIds: [],
  },
  8004: {
    id: 8004,
    name: "Ant1",
    imagePath: "8004",
    life: 5,
    attack: 5,
    description: "",
    skillIds: [],
  },
  8005: {
    id: 8005,
    name: "Ant1",
    imagePath: "8005",
    life: 1,
    attack: 5,
    description: "",
    skillIds: [15],
  },
  8006: {
    id: 8006,
    name: "Ant1",
    imagePath: "8006",
    life: 4,
    attack: 4,
    description: "",
    skillIds: [8],
  },
};
